### ISSUE TITLE
Create orbitdb issue for snapshots bug, and engage with orbitdb on gitter to resolve

### ISSUE THREAD

**Issue by holmesworcester** [ZbayApp/waggle#86]
We saw a bug where ~60% of 1000 snapshot entries failed to load due to timeout, when loading a snapshot. 

Snapshots are one possible approach to achieving fast sync, so we want to make sure they are working.

Let's create an orbitdb issue for this and ask orbitdb folks what's going on.

**Comment by EmiM** [comment]
https://github.com/orbitdb/orbit-db/issues/900 <- this is the issue. I also notified people on gitter

**Comment by EmiM** [comment]
I think there is nothing more to do in this task.
I've prepared two very basic tests (each using one node creating snapshot, the other one retrieving and loading it). One test uses tor and this is the one throwing timeouts, the other one is connecting nodes through localhost (for comparison).
